"""Build the 5-page engineering report PDF using reportlab."""
from __future__ import annotations

import io
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as canvas_mod

from services.documenter.pdf import theme
from services.documenter.pdf.tables import (
    draw_safety_factor_bar,
    draw_table,
    make_kv_table,
    make_table,
)
from services.documenter.pdf.title_block import derive_doc_number
from services.explainer.domain.models import NaturalReport
from services.geometry.domain.artifacts import CachedArtifacts
from services.interpreter.domain.intent import DesignIntent
from services.interpreter.domain.materials import MaterialProperties
from services.physics.domain.models import AnalysisResult

_VERSION = "MechDesign AI · S5 Documenter v0.2"
_DOC_KIND = "ENGINEERING DESIGN REPORT"

_DERIVATIONS: dict[str, str] = {
    "Flywheel_Rim": (
        "Centrifugal stress on a thin rim spinning at angular velocity omega "
        "is sigma = rho * omega^2 * R^2 where rho is density and R is outer "
        "radius. The result is the maximum tangential stress at the periphery."
    ),
    "Pelton_Runner": (
        "Hydraulic power is rho_w*g*Q*H*eta. Optimal bucket speed is "
        "u = 0.46 * sqrt(2*g*H). Shaft torque follows from T = P/omega and the "
        "shear stress on the shaft is tau = 16T/(pi*d^3)."
    ),
    "Hinge_Panel": (
        "Wind pressure is P = C_p * 0.5 * rho_air * v^2. The panel is modeled "
        "as a cantilever loaded by P; bending stress sigma = 6PL^2/t^2 with L "
        "the cantilever length and t the thickness."
    ),
}


def build_report_pdf(
    *,
    intent: DesignIntent,
    analysis: AnalysisResult,
    narrative: NaturalReport,
    geometry: CachedArtifacts,
    material: MaterialProperties,
    svg_bytes: bytes,
    now_utc_iso: str,
    cache_key: str,
) -> bytes:
    """Return PDF bytes for the 5-page engineering report."""
    buf = io.BytesIO()
    c = canvas_mod.Canvas(buf, pagesize=theme.PAGE_SIZE)
    doc_number = derive_doc_number(cache_key)

    _draw_cover(c, intent, analysis, material, doc_number, now_utc_iso)
    _draw_page_chrome(c, page_no=1, total=5, doc_number=doc_number, title=_DOC_KIND)
    c.showPage()

    _draw_intent_and_bom(c, intent, material)
    _draw_page_chrome(c, page_no=2, total=5, doc_number=doc_number, title="DESIGN INTENT · BOM")
    c.showPage()

    _draw_geometry(c, geometry, svg_bytes)
    _draw_page_chrome(c, page_no=3, total=5, doc_number=doc_number, title="GEOMETRY · MASS PROPERTIES")
    c.showPage()

    _draw_analysis(c, analysis)
    _draw_page_chrome(c, page_no=4, total=5, doc_number=doc_number, title="STRUCTURAL ANALYSIS")
    c.showPage()

    _draw_narrative_and_appendix(c, analysis, narrative, material)
    _draw_page_chrome(c, page_no=5, total=5, doc_number=doc_number, title="NARRATIVE · APPENDIX")
    c.showPage()

    c.save()
    return buf.getvalue()


# ============================================================
# COVER
# ============================================================

def _draw_cover(
    c: canvas_mod.Canvas,
    intent: DesignIntent,
    analysis: AnalysisResult,
    material: MaterialProperties,
    doc_number: str,
    now_utc_iso: str,
) -> None:
    width, height = theme.PAGE_SIZE

    # Eggplant header band
    band_h = 54 * mm
    c.setFillColor(theme.BROTEA_EGGPLANT)
    c.rect(0, height - band_h, width, band_h, stroke=0, fill=1)

    # Glow yellow accent stripe
    c.setFillColor(theme.BROTEA_GLOW)
    c.rect(0, height - band_h - 2, width, 2, stroke=0, fill=1)

    # Eyebrow
    c.setFillColor(theme.BROTEA_GLOW)
    c.setFont(*theme.FONT_LABEL)
    c.drawString(theme.MARGIN_PT, height - 18 * mm, _DOC_KIND)

    # Title
    c.setFillColor(colors.white)
    c.setFont(*theme.FONT_TITLE)
    c.drawString(theme.MARGIN_PT, height - 32 * mm, "Mechanical Design Report")

    # Subtitle = intent type + doc number
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.BROTEA_BONE)
    c.drawString(theme.MARGIN_PT, height - 42 * mm, f"{intent.type.replace('_', ' ')}   ·   {doc_number}")

    # Cover summary grid
    summary_top = height - band_h - 12 * mm
    table = make_kv_table(
        [
            ("Document", doc_number),
            ("Subject", intent.type.replace("_", " ")),
            ("Material", material.name.replace("_", " ")),
            ("Date (UTC)", now_utc_iso),
            ("Revision", "R1"),
            ("Status", analysis.verdict.value.upper()),
            ("Generated by", _VERSION),
            ("Standard", "ISO 7200 (title block layout)"),
        ],
        col_widths=[42 * mm, 100 * mm],
    )
    draw_table(c, table, theme.MARGIN_PT, summary_top, max_width=160 * mm)

    # Verdict badge
    verdict = analysis.verdict.value
    badge_color = theme.COLOR_VERDICT.get(verdict, colors.grey)
    badge_w = 70 * mm
    badge_h = 22 * mm
    badge_x = width - theme.MARGIN_PT - badge_w
    badge_y = summary_top - 30 * mm
    c.setFillColor(badge_color)
    c.roundRect(badge_x, badge_y, badge_w, badge_h, 4, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(badge_x + badge_w / 2, badge_y + badge_h / 2 - 4, verdict.upper())
    c.setFont(*theme.FONT_SMALL)
    c.drawCentredString(badge_x + badge_w / 2, badge_y + badge_h / 2 - 14, f"Safety factor {analysis.safety_factor:.2f}")

    # Brand strip near bottom
    c.setFillColor(theme.BROTEA_VIOLET)
    c.rect(0, 38 * mm, width, 4, stroke=0, fill=1)
    c.setFillColor(theme.INK)
    c.setFont(*theme.FONT_LABEL)
    c.drawString(theme.MARGIN_PT, 30 * mm, "MECHDESIGN AI · GEMMA 4 GOOD")
    c.setFillColor(theme.INK_MUTED)
    c.setFont(*theme.FONT_SMALL)
    c.drawString(
        theme.MARGIN_PT,
        24 * mm,
        "Specs and figures in this report are auto-generated from a natural-language intent.",
    )


# ============================================================
# PAGE 2 — DESIGN INTENT + BOM
# ============================================================

def _draw_intent_and_bom(
    c: canvas_mod.Canvas,
    intent: DesignIntent,
    material: MaterialProperties,
) -> None:
    width, height = theme.PAGE_SIZE
    y = height - 30 * mm  # leave room for the running header

    _section_title(c, y, "1. Design Intent")
    y -= 14 * mm

    intent_rows: list[list[str]] = [["Parameter", "Value", "Source", "Original"]]
    for name, field in sorted(intent.fields.items()):
        if field.value is None:
            continue
        value = field.value
        intent_rows.append(
            [
                name,
                f"{value:.4f}" if isinstance(value, (int, float)) else str(value),
                field.source.value,
                field.original or "—",
            ]
        )
    if len(intent_rows) > 1:
        table = make_table(
            intent_rows,
            col_widths=[55 * mm, 35 * mm, 30 * mm, 38 * mm],
            align_right_cols=(1,),
        )
        y = draw_table(c, table, theme.MARGIN_PT, y, max_width=160 * mm)

    y -= 10 * mm
    _section_title(c, y, "2. Bill of Materials")
    y -= 14 * mm

    bom_rows: list[list[str]] = [["Item", "Component", "Qty", "Material", "Role"]]
    bom_rows.append(["1", intent.type.replace("_", " "), "1", material.name.replace("_", " "), "Main"])
    for i, composed in enumerate(intent.composed_of, start=2):
        bom_rows.append(
            [str(i), composed.replace("_", " "), "1", material.name.replace("_", " "), "Companion"]
        )
    table = make_table(
        bom_rows,
        col_widths=[14 * mm, 60 * mm, 14 * mm, 50 * mm, 22 * mm],
        align_right_cols=(2,),
    )
    y = draw_table(c, table, theme.MARGIN_PT, y, max_width=160 * mm)

    y -= 10 * mm
    _section_title(c, y, "3. Material Specification")
    y -= 14 * mm
    mat_rows: list[list[str]] = [["Property", "Value", "Unit"]]
    mat_rows.extend(
        [
            ["Density", f"{material.density_kg_m3:,.0f}", "kg/m³"],
            ["Young modulus", f"{material.young_modulus_gpa:.1f}", "GPa"],
            ["Yield strength", f"{material.yield_strength_mpa:.1f}", "MPa"],
            ["Ultimate tensile", f"{material.ultimate_tensile_strength_mpa:.1f}", "MPa"],
            ["Thermal conductivity", f"{material.thermal_conductivity_w_m_k:.2f}", "W/m·K"],
            ["Max service temp.", f"{material.max_service_temperature_c:.0f}", "°C"],
            ["Relative cost index", f"{material.relative_cost_index:.2f}", "—"],
            ["Sustainability score", f"{material.sustainability_score:.2f}", "—"],
            ["Category", material.category, "—"],
        ]
    )
    table = make_table(
        mat_rows,
        col_widths=[60 * mm, 60 * mm, 30 * mm],
        align_right_cols=(1,),
    )
    draw_table(c, table, theme.MARGIN_PT, y, max_width=160 * mm)


# ============================================================
# PAGE 3 — GEOMETRY + MASS PROPERTIES
# ============================================================

def _draw_geometry(
    c: canvas_mod.Canvas,
    geometry: CachedArtifacts,
    svg_bytes: bytes,
) -> None:
    _, height = theme.PAGE_SIZE
    y = height - 30 * mm

    _section_title(c, y, "4. Mass Properties")
    y -= 14 * mm

    m = geometry.mass_properties
    bbox_w = m.bbox_m[3] - m.bbox_m[0]
    bbox_h = m.bbox_m[4] - m.bbox_m[1]
    bbox_d = m.bbox_m[5] - m.bbox_m[2]

    rows: list[list[str]] = [
        ["Quantity", "Value", "Unit"],
        ["Mass", f"{m.mass_kg:.3f}", "kg"],
        ["Volume", f"{m.volume_m3:.5f}", "m³"],
        [
            "Center of mass",
            f"({m.center_of_mass[0]:.3f}, {m.center_of_mass[1]:.3f}, {m.center_of_mass[2]:.3f})",
            "m",
        ],
        ["Bounding box X", f"{bbox_w:.3f}", "m"],
        ["Bounding box Y", f"{bbox_h:.3f}", "m"],
        ["Bounding box Z", f"{bbox_d:.3f}", "m"],
        [
            "Bbox min (x,y,z)",
            f"({m.bbox_m[0]:.3f}, {m.bbox_m[1]:.3f}, {m.bbox_m[2]:.3f})",
            "m",
        ],
        [
            "Bbox max (x,y,z)",
            f"({m.bbox_m[3]:.3f}, {m.bbox_m[4]:.3f}, {m.bbox_m[5]:.3f})",
            "m",
        ],
    ]
    table = make_table(
        rows,
        col_widths=[60 * mm, 70 * mm, 20 * mm],
        align_right_cols=(1,),
    )
    y = draw_table(c, table, theme.MARGIN_PT, y, max_width=160 * mm)

    y -= 12 * mm
    _section_title(c, y, "5. Section View")
    y -= 6 * mm
    c.setFillColor(theme.INK_MUTED)
    c.setFont(*theme.FONT_SMALL)
    c.drawString(theme.MARGIN_PT, y, "Mid-plane section, viewing along +Z. Dimensions in metres.")
    y -= 4 * mm

    # Drawing frame
    frame_w = 150 * mm
    frame_h = 110 * mm
    c.setStrokeColor(theme.INK)
    c.setLineWidth(theme.LINE_MEDIUM)
    c.rect(theme.MARGIN_PT, y - frame_h, frame_w, frame_h, stroke=1, fill=0)
    embedded = _try_embed_svg(
        c,
        svg_bytes,
        theme.MARGIN_PT + 6,
        y - frame_h + 6,
        frame_w - 12,
        frame_h - 12,
    )
    if not embedded:
        c.setFont(*theme.FONT_BODY)
        c.setFillColor(theme.INK_MUTED)
        c.drawCentredString(
            theme.MARGIN_PT + frame_w / 2,
            y - frame_h / 2,
            f"Section view at {geometry.svg_url}",
        )


# ============================================================
# PAGE 4 — STRUCTURAL ANALYSIS
# ============================================================

def _draw_analysis(
    c: canvas_mod.Canvas,
    analysis: AnalysisResult,
) -> None:
    width, height = theme.PAGE_SIZE
    y = height - 30 * mm

    _section_title(c, y, "6. Structural Analysis")
    y -= 14 * mm

    # Methodology
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Methodology")
    y -= 5 * mm
    c.setFont(*theme.FONT_BODY)
    c.setFillColor(theme.INK_MUTED)
    c.drawString(theme.MARGIN_PT, y, f"Intent: {analysis.intent_type}    Material: {analysis.material_name}")
    y -= 5 * mm
    c.setFont(*theme.FONT_MONO_BOLD)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, f"σ_formula:  {analysis.formula}")
    y -= 8 * mm

    # Results table
    stress_mpa = analysis.stress_max_pa / 1e6
    margin_pct = ((analysis.material_yield_mpa - stress_mpa) / analysis.material_yield_mpa) * 100 if analysis.material_yield_mpa else 0.0
    rows: list[list[str]] = [
        ["Quantity", "Value", "Unit", "Allowable", "Margin"],
        [
            "Max stress (σ_max)",
            f"{stress_mpa:.3f}",
            "MPa",
            f"{analysis.material_yield_mpa:.1f}",
            f"{margin_pct:+.1f}%",
        ],
        [
            "Yield strength",
            f"{analysis.material_yield_mpa:.1f}",
            "MPa",
            "—",
            "—",
        ],
        [
            "Max displacement",
            f"{analysis.displacement_max_m * 1000:.4f}",
            "mm",
            "—",
            "—",
        ],
        [
            "Safety factor (SF)",
            f"{analysis.safety_factor:.2f}",
            "—",
            "≥ 2.0",
            "PASS" if analysis.safety_factor >= 2.0 else ("WARN" if analysis.safety_factor >= 1.5 else "FAIL"),
        ],
    ]
    table = make_table(
        rows,
        col_widths=[55 * mm, 28 * mm, 18 * mm, 32 * mm, 27 * mm],
        align_right_cols=(1, 3),
    )
    y = draw_table(c, table, theme.MARGIN_PT, y, max_width=160 * mm)

    y -= 12 * mm
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Safety Factor Gauge")
    y -= 14 * mm
    draw_safety_factor_bar(
        c,
        theme.MARGIN_PT,
        y,
        width=140 * mm,
        height=8 * mm,
        safety_factor=analysis.safety_factor,
    )
    y -= 18 * mm
    c.setFont(*theme.FONT_SMALL)
    c.setFillColor(theme.INK_MUTED)
    c.drawString(
        theme.MARGIN_PT,
        y,
        "Thresholds: fail < 1.5 (red)   ·   warn 1.5–2.0 (amber)   ·   pass ≥ 2.0 (green)",
    )
    y -= 10 * mm

    # Verdict block
    verdict = analysis.verdict.value
    badge_color = theme.COLOR_VERDICT.get(verdict, colors.grey)
    bw = 80 * mm
    bh = 20 * mm
    bx = theme.MARGIN_PT
    by = y - bh
    c.setFillColor(badge_color)
    c.roundRect(bx, by, bw, bh, 4, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(bx + 6, by + bh / 2 - 3, f"VERDICT: {verdict.upper()}")
    c.setFont(*theme.FONT_SMALL)
    c.drawString(bx + 6, by + 4, f"SF = {analysis.safety_factor:.2f}")

    # Loading conditions
    y = by - 14 * mm
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Loading Conditions")
    y -= 4 * mm
    c.setFont(*theme.FONT_BODY)
    c.setFillColor(theme.INK_MUTED)
    notes = analysis.notes or "Operating condition derived from the design intent (see §1)."
    y = _draw_wrapped(c, notes, theme.MARGIN_PT, y - 4 * mm, max_width=width - 2 * theme.MARGIN_PT)


# ============================================================
# PAGE 5 — NARRATIVE + APPENDIX
# ============================================================

def _draw_narrative_and_appendix(
    c: canvas_mod.Canvas,
    analysis: AnalysisResult,
    narrative: NaturalReport,
    material: MaterialProperties,
) -> None:
    width, height = theme.PAGE_SIZE
    y = height - 30 * mm

    _section_title(c, y, "7. Engineering Narrative")
    y -= 14 * mm

    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Summary")
    y -= 5 * mm
    c.setFont(*theme.FONT_BODY)
    c.setFillColor(theme.INK)
    y = _draw_wrapped(c, narrative.summary, theme.MARGIN_PT, y, width - 2 * theme.MARGIN_PT)

    for heading, items in (
        ("Risks", narrative.risks),
        ("Recommendations", narrative.suggestions),
        ("Engineering analogies", narrative.analogies),
    ):
        if not items:
            continue
        y -= 4 * mm
        c.setFont(*theme.FONT_H2)
        c.setFillColor(theme.INK)
        c.drawString(theme.MARGIN_PT, y, heading)
        y -= 5 * mm
        c.setFont(*theme.FONT_BODY)
        c.setFillColor(theme.INK)
        for item in items:
            y = _draw_wrapped(c, f"·  {item}", theme.MARGIN_PT + 4, y, width - 2 * theme.MARGIN_PT - 4)
            y -= 1 * mm

    y -= 6 * mm
    _section_title(c, y, "8. Appendix — Formula Derivation")
    y -= 12 * mm
    c.setFont(*theme.FONT_MONO_BOLD)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, analysis.formula)
    y -= 6 * mm
    c.setFont(*theme.FONT_BODY)
    c.setFillColor(theme.INK)
    derivation = _DERIVATIONS.get(
        analysis.intent_type,
        "Derivation reference: see docs/superpowers/specs/2026-05-16-s3-physics-design.md.",
    )
    y = _draw_wrapped(c, derivation, theme.MARGIN_PT, y, width - 2 * theme.MARGIN_PT)

    y -= 6 * mm
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Facts cited by narrative")
    y -= 5 * mm
    c.setFont(*theme.FONT_MONO)
    c.setFillColor(theme.INK_MUTED)
    y = _draw_wrapped(
        c,
        ", ".join(narrative.facts_used) or "—",
        theme.MARGIN_PT,
        y,
        width - 2 * theme.MARGIN_PT,
    )

    y -= 6 * mm
    c.setFont(*theme.FONT_H2)
    c.setFillColor(theme.INK)
    c.drawString(theme.MARGIN_PT, y, "Approvals")
    y -= 14 * mm
    # Signature lines
    line_w = 60 * mm
    c.setStrokeColor(theme.INK)
    c.setLineWidth(theme.LINE_MEDIUM)
    for i, role in enumerate(("Drawn by", "Checked by", "Approved by")):
        x = theme.MARGIN_PT + i * (line_w + 6 * mm)
        c.line(x, y, x + line_w, y)
        c.setFont(*theme.FONT_SMALL)
        c.setFillColor(theme.INK_MUTED)
        c.drawString(x, y - 4 * mm, role.upper())
        c.setFont(*theme.FONT_BODY)
        c.setFillColor(theme.INK)
        default = (
            "MechDesign AI"
            if role == "Drawn by"
            else "Gemma 4"
            if role == "Checked by"
            else "—"
        )
        c.drawString(x, y + 2, default)


# ============================================================
# HELPERS
# ============================================================

def _section_title(c: canvas_mod.Canvas, y: float, label: str) -> None:
    c.setFillColor(theme.BROTEA_EGGPLANT)
    c.rect(theme.MARGIN_PT - 4, y - 1, 4, 8 * mm, stroke=0, fill=1)
    c.setFillColor(theme.INK)
    c.setFont(*theme.FONT_H1)
    c.drawString(theme.MARGIN_PT + 4, y + 1, label)


def _draw_page_chrome(
    c: canvas_mod.Canvas,
    *,
    page_no: int,
    total: int,
    doc_number: str,
    title: str,
) -> None:
    """Draw running header + footer on the current page."""
    width, height = theme.PAGE_SIZE
    # Top rule + crumbs (skip on cover)
    if page_no > 1:
        c.setStrokeColor(theme.RULE)
        c.setLineWidth(theme.LINE_THIN)
        c.line(theme.MARGIN_PT, height - 18 * mm, width - theme.MARGIN_PT, height - 18 * mm)
        c.setFillColor(theme.INK_MUTED)
        c.setFont(*theme.FONT_LABEL)
        c.drawString(theme.MARGIN_PT, height - 14 * mm, f"MECHDESIGN AI  ·  {doc_number}")
        c.drawRightString(width - theme.MARGIN_PT, height - 14 * mm, title)

    # Bottom rule + meta
    c.setStrokeColor(theme.RULE)
    c.setLineWidth(theme.LINE_THIN)
    c.line(theme.MARGIN_PT, 16 * mm, width - theme.MARGIN_PT, 16 * mm)
    c.setFillColor(theme.INK_MUTED)
    c.setFont(*theme.FONT_LABEL)
    c.drawString(theme.MARGIN_PT, 12 * mm, _VERSION)
    c.drawRightString(width - theme.MARGIN_PT, 12 * mm, f"Page {page_no} / {total}")
    c.drawCentredString(width / 2, 12 * mm, f"Generated {datetime.now(tz=UTC).strftime('%Y-%m-%d %H:%MZ')}")


def _try_embed_svg(
    c: canvas_mod.Canvas,
    svg_bytes: bytes,
    x: float,
    y: float,
    w: float,
    h: float,
) -> bool:
    try:
        from reportlab.graphics import renderPDF
        from svglib.svglib import svg2rlg  # type: ignore[import-not-found]
    except ImportError:
        return False
    try:
        drawing = svg2rlg(io.BytesIO(svg_bytes))
        if drawing is None:
            return False
        scale_x = w / drawing.width if drawing.width else 1.0
        scale_y = h / drawing.height if drawing.height else 1.0
        scale = min(scale_x, scale_y)
        drawing.scale(scale, scale)
        renderPDF.draw(drawing, c, x, y)
        return True
    except Exception:
        return False


def _draw_wrapped(
    c: canvas_mod.Canvas,
    text: str,
    x: float,
    y: float,
    max_width: float,
    line_height: float = 11.5,
) -> float:
    """Naive word-wrap with the current font."""
    words = text.split()
    if not words:
        return y
    line = ""
    font_name, font_size = c._fontname, c._fontsize  # type: ignore[attr-defined]
    for w in words:
        candidate = (line + " " + w).strip()
        if c.stringWidth(candidate, font_name, font_size) <= max_width:
            line = candidate
        else:
            c.drawString(x, y, line)
            y -= line_height
            line = w
    if line:
        c.drawString(x, y, line)
        y -= line_height
    return y
